import mongoose from "mongoose";
import dotenv from "dotenv";
import { connectDB } from "../config/db";
import { Ticket } from "../models/Ticket";

dotenv.config();

const tickets = [
  {
    departureCity: "Almaty",
    destinationCity: "Astana",
    price: 126,
    departureDate: new Date("2025-06-15T07:25:00Z"),
    arrivalTime: "11:00 am",
    travelTime: "5.5h",
    airline: "Air Astana",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    isHotTicket: true,
    returnDate: null,
  },
  {
    departureCity: "Almaty",
    destinationCity: "Astana",
    price: 130,
    departureDate: new Date("2025-06-16T10:00:00Z"),
    arrivalTime: "1:30 pm",
    travelTime: "5.5h",
    airline: "Scat Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-06-20T15:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Ankara",
    price: 250,
    departureDate: new Date("2025-07-01T09:00:00Z"),
    arrivalTime: "7:30 pm",
    travelTime: "10.5h",
    airline: "Turkish Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    isHotTicket: true,
    returnDate: null,
  },
  {
    departureCity: "Almaty",
    destinationCity: "Antalya",
    price: 280,
    departureDate: new Date("2025-07-10T14:00:00Z"),
    arrivalTime: "1:00 am",
    travelTime: "10.0h",
    airline: "Pegasus Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: false,
    isHotTicket: true,
    returnDate: new Date("2025-07-17T18:00:00Z"),
  },
  {
    departureCity: "Astana",
    destinationCity: "Almaty",
    price: 110,
    departureDate: new Date("2025-06-20T08:00:00Z"),
    arrivalTime: "1:30 pm",
    travelTime: "5.5h",
    airline: "Air Astana",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Shymkent",
    destinationCity: "Almaty",
    price: 80,
    departureDate: new Date("2025-06-22T09:00:00Z"),
    arrivalTime: "11:00 am",
    travelTime: "2.0h",
    airline: "FlyArystan",
    baggage: "1x15kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-06-25T14:00:00Z"),
  },
  // Additional Kazakhstan domestic flights (20 more)
  {
    departureCity: "Almaty",
    destinationCity: "Shymkent",
    price: 90,
    departureDate: new Date("2025-06-25T12:00:00Z"),
    arrivalTime: "2:00 pm",
    travelTime: "2.0h",
    airline: "FlyArystan",
    baggage: "1x15kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Shymkent",
    price: 100,
    departureDate: new Date("2025-06-26T09:30:00Z"),
    arrivalTime: "12:30 pm",
    travelTime: "3.0h",
    airline: "Scat Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-06-28T16:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Aktau",
    price: 180,
    departureDate: new Date("2025-06-28T06:00:00Z"),
    arrivalTime: "9:00 am",
    travelTime: "3.0h",
    airline: "Air Astana",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Aktau",
    destinationCity: "Almaty",
    price: 175,
    departureDate: new Date("2025-06-29T18:00:00Z"),
    arrivalTime: "9:00 pm",
    travelTime: "3.0h",
    airline: "FlyArystan",
    baggage: "1x15kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: new Date("2025-07-02T10:00:00Z"),
  },
  {
    departureCity: "Astana",
    destinationCity: "Atyrau",
    price: 150,
    departureDate: new Date("2025-07-02T10:00:00Z"),
    arrivalTime: "12:30 pm",
    travelTime: "2.5h",
    airline: "Scat Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: null,
  },
  {
    departureCity: "Atyrau",
    destinationCity: "Astana",
    price: 145,
    departureDate: new Date("2025-07-03T14:00:00Z"),
    arrivalTime: "4:30 pm",
    travelTime: "2.5h",
    airline: "Air Astana",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: new Date("2025-07-05T18:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Ust-Kamenogorsk",
    price: 110,
    departureDate: new Date("2025-07-05T08:00:00Z"),
    arrivalTime: "10:00 am",
    travelTime: "2.0h",
    airline: "FlyArystan",
    baggage: "1x15kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Ust-Kamenogorsk",
    destinationCity: "Almaty",
    price: 105,
    departureDate: new Date("2025-07-06T16:00:00Z"),
    arrivalTime: "6:00 pm",
    travelTime: "2.0h",
    airline: "Scat Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-07-08T10:00:00Z"),
  },
  {
    departureCity: "Astana",
    destinationCity: "Karaganda",
    price: 70,
    departureDate: new Date("2025-07-08T07:00:00Z"),
    arrivalTime: "8:00 am",
    travelTime: "1.0h",
    airline: "Air Astana",
    baggage: "1x10kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Karaganda",
    destinationCity: "Astana",
    price: 65,
    departureDate: new Date("2025-07-09T19:00:00Z"),
    arrivalTime: "8:00 pm",
    travelTime: "1.0h",
    airline: "FlyArystan",
    baggage: "1x10kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-07-11T12:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Aktobe",
    price: 160,
    departureDate: new Date("2025-07-11T11:00:00Z"),
    arrivalTime: "1:30 pm",
    travelTime: "2.5h",
    airline: "Scat Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Aktobe",
    destinationCity: "Almaty",
    price: 155,
    departureDate: new Date("2025-07-12T15:00:00Z"),
    arrivalTime: "5:30 pm",
    travelTime: "2.5h",
    airline: "Air Astana",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-07-14T10:00:00Z"),
  },
  {
    departureCity: "Astana",
    destinationCity: "Kyzylorda",
    price: 130,
    departureDate: new Date("2025-07-14T09:00:00Z"),
    arrivalTime: "11:00 am",
    travelTime: "2.0h",
    airline: "FlyArystan",
    baggage: "1x15kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Kyzylorda",
    destinationCity: "Astana",
    price: 125,
    departureDate: new Date("2025-07-15T13:00:00Z"),
    arrivalTime: "3:00 pm",
    travelTime: "2.0h",
    airline: "Scat Airlines",
    baggage: "1x15kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-07-17T17:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Semey",
    price: 100,
    departureDate: new Date("2025-07-17T07:00:00Z"),
    arrivalTime: "9:00 am",
    travelTime: "2.0h",
    airline: "Air Astana",
    baggage: "1x15kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Semey",
    destinationCity: "Almaty",
    price: 95,
    departureDate: new Date("2025-07-18T14:00:00Z"),
    arrivalTime: "4:00 pm",
    travelTime: "2.0h",
    airline: "FlyArystan",
    baggage: "1x15kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-07-20T11:00:00Z"),
  },
  {
    departureCity: "Astana",
    destinationCity: "Pavlodar",
    price: 80,
    departureDate: new Date("2025-07-20T10:00:00Z"),
    arrivalTime: "11:30 am",
    travelTime: "1.5h",
    airline: "Scat Airlines",
    baggage: "1x10kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Pavlodar",
    destinationCity: "Astana",
    price: 75,
    departureDate: new Date("2025-07-21T16:00:00Z"),
    arrivalTime: "5:30 pm",
    travelTime: "1.5h",
    airline: "Air Astana",
    baggage: "1x10kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-07-23T09:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Uralsk",
    price: 200,
    departureDate: new Date("2025-07-23T09:00:00Z"),
    arrivalTime: "12:00 pm",
    travelTime: "3.0h",
    airline: "FlyArystan",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Uralsk",
    destinationCity: "Almaty",
    price: 195,
    departureDate: new Date("2025-07-24T13:00:00Z"),
    arrivalTime: "4:00 pm",
    travelTime: "3.0h",
    airline: "Scat Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-07-26T18:00:00Z"),
  },
  // International flights (30 more)
  {
    departureCity: "Astana",
    destinationCity: "Dubai",
    price: 350,
    departureDate: new Date("2025-08-01T10:00:00Z"),
    arrivalTime: "2:00 pm",
    travelTime: "4.0h",
    airline: "FlyDubai",
    baggage: "1x25kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    isHotTicket: true,
    returnDate: new Date("2025-08-08T15:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Istanbul",
    price: 300,
    departureDate: new Date("2025-08-05T08:00:00Z"),
    arrivalTime: "12:00 pm",
    travelTime: "4.0h",
    airline: "Turkish Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    isHotTicket: true,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Moscow",
    price: 200,
    departureDate: new Date("2025-08-10T11:00:00Z"),
    arrivalTime: "1:00 pm",
    travelTime: "2.0h",
    airline: "Aeroflot",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-08-15T16:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "London",
    price: 500,
    departureDate: new Date("2025-08-12T09:00:00Z"),
    arrivalTime: "1:00 pm",
    travelTime: "8.0h",
    airline: "British Airways",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    isHotTicket: true,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Frankfurt",
    price: 450,
    departureDate: new Date("2025-08-18T14:00:00Z"),
    arrivalTime: "6:00 pm",
    travelTime: "6.0h",
    airline: "Lufthansa",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: new Date("2025-08-25T10:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Beijing",
    price: 280,
    departureDate: new Date("2025-08-20T10:00:00Z"),
    arrivalTime: "2:00 pm",
    travelTime: "4.0h",
    airline: "Air China",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Seoul",
    price: 400,
    departureDate: new Date("2025-08-22T09:00:00Z"),
    arrivalTime: "5:00 pm",
    travelTime: "8.0h",
    airline: "Asiana Airlines",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    isHotTicket: true,
    returnDate: new Date("2025-08-29T14:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Delhi",
    price: 220,
    departureDate: new Date("2025-08-25T13:00:00Z"),
    arrivalTime: "6:00 pm",
    travelTime: "4.0h",
    airline: "IndiGo",
    baggage: "1x15kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Tashkent",
    price: 150,
    departureDate: new Date("2025-08-28T07:00:00Z"),
    arrivalTime: "8:30 am",
    travelTime: "1.5h",
    airline: "Uzbekistan Airways",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: new Date("2025-08-30T10:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Bishkek",
    price: 100,
    departureDate: new Date("2025-09-01T09:00:00Z"),
    arrivalTime: "10:00 am",
    travelTime: "1.0h",
    airline: "Air Kyrgyzstan",
    baggage: "1x15kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Baku",
    price: 250,
    departureDate: new Date("2025-09-03T11:00:00Z"),
    arrivalTime: "2:00 pm",
    travelTime: "3.0h",
    airline: "Azerbaijan Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: new Date("2025-09-06T15:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Dushanbe",
    price: 180,
    departureDate: new Date("2025-09-06T08:00:00Z"),
    arrivalTime: "10:00 am",
    travelTime: "2.0h",
    airline: "Somon Air",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Minsk",
    price: 300,
    departureDate: new Date("2025-09-08T10:00:00Z"),
    arrivalTime: "1:00 pm",
    travelTime: "3.0h",
    airline: "Belavia",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: new Date("2025-09-12T16:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Tbilisi",
    price: 280,
    departureDate: new Date("2025-09-10T12:00:00Z"),
    arrivalTime: "3:00 pm",
    travelTime: "3.0h",
    airline: "Georgian Airways",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Kyiv",
    price: 270,
    departureDate: new Date("2025-09-13T09:00:00Z"),
    arrivalTime: "12:00 pm",
    travelTime: "3.0h",
    airline: "Ukraine International Airlines",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-09-16T15:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Warsaw",
    price: 350,
    departureDate: new Date("2025-09-15T11:00:00Z"),
    arrivalTime: "3:00 pm",
    travelTime: "4.0h",
    airline: "LOT Polish Airlines",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Budapest",
    price: 320,
    departureDate: new Date("2025-09-18T10:00:00Z"),
    arrivalTime: "2:00 pm",
    travelTime: "4.0h",
    airline: "Wizz Air",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-09-22T14:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Prague",
    price: 330,
    departureDate: new Date("2025-09-20T08:00:00Z"),
    arrivalTime: "12:00 pm",
    travelTime: "4.0h",
    airline: "Czech Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Vienna",
    price: 310,
    departureDate: new Date("2025-09-23T13:00:00Z"),
    arrivalTime: "5:00 pm",
    travelTime: "4.0h",
    airline: "Austrian Airlines",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: new Date("2025-09-27T18:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Rome",
    price: 400,
    departureDate: new Date("2025-09-25T10:00:00Z"),
    arrivalTime: "2:00 pm",
    travelTime: "4.0h",
    airline: "ITA Airways",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Milan",
    price: 380,
    departureDate: new Date("2025-09-28T09:00:00Z"),
    arrivalTime: "1:00 pm",
    travelTime: "4.0h",
    airline: "Ryanair",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: new Date("2025-10-02T16:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Barcelona",
    price: 420,
    departureDate: new Date("2025-10-01T11:00:00Z"),
    arrivalTime: "4:00 pm",
    travelTime: "5.0h",
    airline: "Vueling",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Madrid",
    price: 410,
    departureDate: new Date("2025-10-04T10:00:00Z"),
    arrivalTime: "3:00 pm",
    travelTime: "5.0h",
    airline: "Iberia",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-10-08T17:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Amsterdam",
    price: 390,
    departureDate: new Date("2025-10-06T09:00:00Z"),
    arrivalTime: "1:00 pm",
    travelTime: "4.0h",
    airline: "KLM",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Brussels",
    price: 360,
    departureDate: new Date("2025-10-09T14:00:00Z"),
    arrivalTime: "6:00 pm",
    travelTime: "4.0h",
    airline: "Brussels Airlines",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-10-13T10:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Zurich",
    price: 370,
    departureDate: new Date("2025-10-11T11:00:00Z"),
    arrivalTime: "3:00 pm",
    travelTime: "4.0h",
    airline: "SWISS",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Lisbon",
    price: 430,
    departureDate: new Date("2025-10-14T10:00:00Z"),
    arrivalTime: "3:00 pm",
    travelTime: "5.0h",
    airline: "TAP Air Portugal",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-10-18T16:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Stockholm",
    price: 340,
    departureDate: new Date("2025-10-16T08:00:00Z"),
    arrivalTime: "12:00 pm",
    travelTime: "4.0h",
    airline: "SAS",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Oslo",
    price: 330,
    departureDate: new Date("2025-10-19T13:00:00Z"),
    arrivalTime: "5:00 pm",
    travelTime: "4.0h",
    airline: "Norwegian Air Shuttle",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-10-23T09:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Copenhagen",
    price: 350,
    departureDate: new Date("2025-10-21T09:00:00Z"),
    arrivalTime: "1:00 pm",
    travelTime: "4.0h",
    airline: "SAS",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Helsinki",
    price: 360,
    departureDate: new Date("2025-10-24T12:00:00Z"),
    arrivalTime: "4:00 pm",
    travelTime: "4.0h",
    airline: "Finnair",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-10-28T15:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Athens",
    price: 380,
    departureDate: new Date("2025-10-26T10:00:00Z"),
    arrivalTime: "2:00 pm",
    travelTime: "4.0h",
    airline: "Aegean Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Dublin",
    price: 400,
    departureDate: new Date("2025-10-29T08:00:00Z"),
    arrivalTime: "1:00 pm",
    travelTime: "5.0h",
    airline: "Aer Lingus",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-11-02T16:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Reykjavik",
    price: 500,
    departureDate: new Date("2025-11-01T09:00:00Z"),
    arrivalTime: "2:00 pm",
    travelTime: "6.0h",
    airline: "Icelandair",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Cairo",
    price: 300,
    departureDate: new Date("2025-11-04T14:00:00Z"),
    arrivalTime: "7:00 pm",
    travelTime: "5.0h",
    airline: "EgyptAir",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-11-08T10:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Amman",
    price: 250,
    departureDate: new Date("2025-11-06T10:00:00Z"),
    arrivalTime: "1:00 pm",
    travelTime: "3.0h",
    airline: "Royal Jordanian",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Doha",
    price: 380,
    departureDate: new Date("2025-11-09T11:00:00Z"),
    arrivalTime: "2:00 pm",
    travelTime: "3.0h",
    airline: "Qatar Airways",
    baggage: "1x25kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-11-13T15:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Manila",
    price: 550,
    departureDate: new Date("2025-11-11T09:00:00Z"),
    arrivalTime: "8:00 pm",
    travelTime: "11.0h",
    airline: "Philippine Airlines",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Bangkok",
    price: 450,
    departureDate: new Date("2025-11-14T13:00:00Z"),
    arrivalTime: "9:00 pm",
    travelTime: "6.0h",
    airline: "Thai Airways",
    baggage: "1x25kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-11-20T14:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Singapore",
    price: 500,
    departureDate: new Date("2025-11-16T10:00:00Z"),
    arrivalTime: "7:00 pm",
    travelTime: "9.0h",
    airline: "Singapore Airlines",
    baggage: "1x25kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Kuala Lumpur",
    price: 480,
    departureDate: new Date("2025-11-19T11:00:00Z"),
    arrivalTime: "7:00 pm",
    travelTime: "8.0h",
    airline: "Malaysia Airlines",
    baggage: "1x25kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-11-25T12:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Jakarta",
    price: 520,
    departureDate: new Date("2025-11-21T08:00:00Z"),
    arrivalTime: "4:00 pm",
    travelTime: "8.0h",
    airline: "Garuda Indonesia",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Hanoi",
    price: 470,
    departureDate: new Date("2025-11-24T10:00:00Z"),
    arrivalTime: "5:00 pm",
    travelTime: "7.0h",
    airline: "Vietnam Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-11-30T10:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Ho Chi Minh City",
    price: 490,
    departureDate: new Date("2025-11-26T09:00:00Z"),
    arrivalTime: "4:00 pm",
    travelTime: "7.0h",
    airline: "Vietjet Air",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Phuket",
    price: 420,
    departureDate: new Date("2025-11-29T13:00:00Z"),
    arrivalTime: "8:00 pm",
    travelTime: "6.0h",
    airline: "Thai Lion Air",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-12-05T14:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Dubai",
    price: 340,
    departureDate: new Date("2025-12-01T07:00:00Z"),
    arrivalTime: "11:00 am",
    travelTime: "4.0h",
    airline: "Air Arabia",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Istanbul",
    price: 290,
    departureDate: new Date("2025-12-04T10:00:00Z"),
    arrivalTime: "2:00 pm",
    travelTime: "4.0h",
    airline: "AnadoluJet",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-12-08T16:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Moscow",
    price: 190,
    departureDate: new Date("2025-12-06T12:00:00Z"),
    arrivalTime: "2:00 pm",
    travelTime: "2.0h",
    airline: "S7 Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "London",
    price: 490,
    departureDate: new Date("2025-12-09T08:00:00Z"),
    arrivalTime: "12:00 pm",
    travelTime: "8.0h",
    airline: "Wizz Air",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-12-15T15:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Frankfurt",
    price: 440,
    departureDate: new Date("2025-12-11T14:00:00Z"),
    arrivalTime: "6:00 pm",
    travelTime: "6.0h",
    airline: "Condor",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Beijing",
    price: 270,
    departureDate: new Date("2025-12-14T10:00:00Z"),
    arrivalTime: "2:00 pm",
    travelTime: "4.0h",
    airline: "China Southern Airlines",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-12-18T16:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Seoul",
    price: 390,
    departureDate: new Date("2025-12-16T09:00:00Z"),
    arrivalTime: "5:00 pm",
    travelTime: "8.0h",
    airline: "Korean Air",
    baggage: "1x23kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Delhi",
    price: 210,
    departureDate: new Date("2025-12-19T13:00:00Z"),
    arrivalTime: "6:00 pm",
    travelTime: "4.0h",
    airline: "Air India",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-12-23T10:00:00Z"),
  },
  {
    departureCity: "Almaty",
    destinationCity: "Tashkent",
    price: 140,
    departureDate: new Date("2025-12-21T07:00:00Z"),
    arrivalTime: "8:30 am",
    travelTime: "1.5h",
    airline: "Uzbekistan Airways",
    baggage: "1x20kg",
    carryOn: true,
    exchangeable: true,
    nonRefundable: false,
    returnDate: null,
  },
  {
    departureCity: "Astana",
    destinationCity: "Bishkek",
    price: 90,
    departureDate: new Date("2025-12-24T09:00:00Z"),
    arrivalTime: "10:00 am",
    travelTime: "1.0h",
    airline: "Avia Traffic Company",
    baggage: "1x15kg",
    carryOn: true,
    exchangeable: false,
    nonRefundable: true,
    returnDate: new Date("2025-12-27T12:00:00Z"),
  },
];

const importData = async () => {
  try {
    await Ticket.deleteMany({});
    await Ticket.insertMany(tickets);
    console.log("Data Imported!");
    process.exit();
  } catch (error) {
    console.error(`${error}`);
    process.exit(1);
  }
};

const destroyData = async () => {
  try {
    await Ticket.deleteMany({});
    console.log("Data Destroyed!");
    process.exit();
  } catch (error) {
    console.error(`${error}`);
    process.exit(1);
  }
};

if (process.argv[2] === "-d") {
  destroyData();
} else {
  importData();
}
